# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
 
# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
 
default_platform(:ios)-
 
platform :ios do
  desc "Description of what the lane does"
  lane :CI do
      run_tests(project: "CIDemoProject.xcodeproj",
      devices: ["iPhone 6s"],
      scheme: "CIDemoProject")
  end
 
  lane :CD do |values|
 
    gym(scheme: 'CIDemoProject', project: "CIDemoProject.xcodeproj", clean: true, silent: true, include_bitcode: false, export_method: 'ad-hoc')
 
    emails = values[:test_email] ? values[:test_email] : ['urvish.patel@agileinfoways.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
 
    crashlytics(api_token: ' 64f680703d113c09f4efd9a5342151b22fb943e6',
             build_secret: ' 3147f3a36113a878e852c4601963ad2f87bd87633a9ff3f91c9b0e10e8ac660c',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
 
    end
end


